test
dustCoding/apple pull request #18
Opened 2022-08-17 12:59 UTC by ExplosiveCocktale

test

2022-08-17 13:00 UTC, minji0401 requested changes
확장자 고쳐줘여

2022-08-17 13:01 UTC, hdev1004 submitted a review, later dismissed
리뷰 추가

2022-08-21 00:14 UTC, minji0401 approved these changes
굿굿 확인!

2022-08-21 09:28 UTC, dev-woong approved these changes
수정 확인했습니다!

2022-08-21 09:29 UTC, dev-woong approved these changes
요거 변경 완료

2022-08-21 09:30 UTC, merged